name: matapass
description: A Very Good Project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  amplify_auth_cognito: ^1.7.2
  amplify_flutter: ^1.7.0
  bloc: ^8.1.3
  cloud_firestore: ^4.17.0
  data_table_2: ^2.5.12
  dio: ^5.4.3+1
  easy_sidemenu: ^0.6.0
  equatable: ^2.0.5
  file_picker: ^5.2.3
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.0
  firebase_storage: ^11.7.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_form_builder: ^9.2.1
  flutter_gen: any
  flutter_image_compress: ^2.2.0
  flutter_localizations:
    sdk: flutter
  flutter_rounded_progress_bar: ^0.3.2
  flutter_tesseract_ocr: ^0.4.24
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.3
  intl: ^0.19.0
  loading_animation_widget: ^1.2.1

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
